<img src='https://www.freecodecamp.org/espanol/news/content/images/2021/04/numpy-1-1-.png' width=400 />

Esta es una introducción a la biblioteca NumPy (**Numerical Python**) de Python. Se trata de una colección de módulos de código abierto que tiene aplicaciones en casi todos los campos de las ciencias y de la ingeniería. Es el estándar para trabajar con datos numéricos en Python. Muchas otras bibliotecas y módulos de Python como Pandas, SciPy, Matplotlib, scikit-learn, scikit-image usan numpy.
<br><br>


Esta biblioteca permite trabajar cómodamente con arreglos multidimensionales mediante el tipo **ndarray**, un objeto n-dimensional homogéneo (es decir, con todas sus entradas del mismo tipo), y con métodos para operar eficientemente sobre él.
<br>
Numpy puede usarse para una amplia variedad de operaciones matemáticas sobre matrices. Le agrega a Python estructuras de datos muy potentes sobre las que puedés hacer cálculos y operar matemáticamente con eficiencia y a un alto nivel.

La documentación oficial la podes encontrar en: https://numpy.org/

## Instalar e importar numpy

Cuando quieras usar numpy en Python, primero tenés que importarlo:

In [2]:
import numpy as np

Acortamos `numpy` a `np` para ahorrar tiempo y mantener el código estandarizado. Todos escriben `np`.

Si no lo tenés instalado en tu máquina (ya que Colab ya lo tiene instalado) podés instalarlo escribiendo el siguiente comando:<br> `!pip install numpy`

## ¿Cuál es la diferencia entre listas y arreglos?

Numpy ofrece varias formas muy eficientes de crear vectores y manipular datos numéricos. Mientras que una lista de Python puede contener diferentes tipos de datos en su interior, los elementos de un vector numpy serán todos del mismo tipo. De esta forma numpy garantiza un muy alto rendimiento en las operaciones matemáticas.

Además, los arreglos están pensados para tener un tamaño fijo, mientras que las listas están diseñadas para agregar y sacar elementos. Son estructuras de datos similares desde un punto de vista superficial, pero muy diferentes en cuanto a las posibilidades que brindan.

Las operaciones matemáticas sobre vectores de numpy son más rápidas que sobre listas. Además los vectores ocupan menos memoria que las listas análogas. En cambio, modificar el tamaño de una lista es algo muy sencillo mientras que el de un vector es costoso. Y combinar diferentes tipos de datos es sencillo en las listas pero imposible en los vectores de numpy.

## Arreglos n-dimensionales

Los vectores (unidimensionales) y matrices (bidimensiones) se generalizan a arreglos n-dimensionales. Esta estructura de datos es la central de la biblioteca numpy. Un arreglo (`ndarray`) tiene una grilla de valores (datos crudos) junto con información sobre cómo ubicarlos y cómo interpretarlos. Los elementos de esta grilla pueden ser indexados de diversas maneras y, como ya dijimos, son todos del mismo tipo. Este tipo es frecuentemente abreviado como `dtype` (por data type).

Un arreglo puede ser indexado por tuplas de enteros no negativos, por variables booleanas, por otro arreglo o por enteros. El rango (`rank`) de un arreglo es su número de dimensiones. Su forma (`shape`) es una tupla de enteros que dice su tamaño en cada dimensión.

Una forma de inicializar un arreglo de numpy es mediante una lista de números. Esto nos da un vector (arreglo de dimensión uno). Usando listas anidadas, podemos definir arreglos de más altas dimensiones.

Por ejemplo:

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [4]:
type(a)

numpy.ndarray

o:

In [6]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
a.shape

(3, 4)

Podemos acceder a los elementos de un arreglo usando corchetes. Acordate que los índices comienzan a contar en 0. Esto significa que si querés acceder al primer elemento, vas a acceder al elemento “0”.

In [8]:
print(a[0]) # si tiene múltiples dimensiones, esto me da una "rebanada" de una dimensión menos
print(a[2]) # otra rebanada
print(a[2][3]) # accedo al cuarto elemento del tercer vector de a
print(a[2,3]) # o, equivalentemente, accedo al elemento en la tercera fila y cuarta columna de a

[1 2 3 4]
[ 9 10 11 12]
12
12


## Más información sobre arreglos

Ocasionalmente vas a ver que alguien se refiere a un arreglo como un  “ndarray” que es una forma breve de decir arreglo n-dimensional. Un arreglo n-dimensional es simplemente un arreglo con n dimensiones. Recordemos que cuando son unidimensionales los llamamos vectores y si son bidimensionales los llamamos matrices.

**¿Qué atributos tiene un arreglo?**

Un arreglo es usualmente un contenedor de tamaño fijo de elementos del mismo tipo. Su forma (shape) es una tupla de enteros no negativos que especifica el tamaño del arreglo en cada dimensión. Un arreglo tiene tantas dimensiones como coordenadas en la tupla.

En numpy, las dimensiones se llaman **axes** (ejes). Esto significa que si tenés un arreglo bidimensional que se ve así:

```
[[0., 0., 0.],
 [1., 1., 1.]]
```

el arreglo tendrá dos ejes. El primer eje tiene tamaño dos, el segundo tamaño tres (sí, se cuentan primero filas, luego columnas).

De la misma forma que los otros objetos contenedores de Python, los elementos de un arreglo pueden ser accedidos y modificados usando índices y rebanadas.

## Crear un arreglo básico

Para crear un arreglo de numpy podés usar la función `np.array()`.
Lo único que necesitás es pasarle una lista. Si querés, podés especificar el tipo de datos que querés que tenga.

In [9]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


Vamos a representar la creación con este gráfico:

<img src='https://raw.githubusercontent.com/mfares07/Programacion_en_Python_UNSAM/master/Notas/05_Random_Plt_Dbg/np_array.png' />

_Ojo, estas visualizaciones son simplificaciones para representar lo que esta pasando y darte un entendimiento básico de los conceptos y mecanismos de numpy. Los arreglos y sus operaciones tienen aspectos más complejos que los que quedan capturados en estos dibujitos._

Además de crear un arreglo a partir de una secuencia de elementos, podés crear un arreglo lleno de `0`’s:

In [10]:
print(np.zeros(20))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


O uno lleno de `1`’s:

In [11]:
print(np.ones(12))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


También podés crear vectores a partir de un rango de valores:

In [15]:
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [16]:
print(np.arange(5,100,3))

[ 5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74
 77 80 83 86 89 92 95 98]


También un vector que contiene elementos equiespaciados, especificando el **primer número**, el **límite**, y el **paso**.

También podés usar `np.linspace()` para crear un vector de valores equiespaciados especificando el **primer número**, el **último número**, y la **cantidad** de elementos:

In [22]:
print(np.linspace(0, 1000, num=41))

[    0.   250.   500.   750.  1000.  1250.  1500.  1750.  2000.  2250.
  2500.  2750.  3000.  3250.  3500.  3750.  4000.  4250.  4500.  4750.
  5000.  5250.  5500.  5750.  6000.  6250.  6500.  6750.  7000.  7250.
  7500.  7750.  8000.  8250.  8500.  8750.  9000.  9250.  9500.  9750.
 10000.]


### Ejercicio: arange() y linspace()
Generá un vector que tenga los números impares entre el 1 y el 19 inclusive usando `arange()`. Repetí el ejercicio usando `linspace()`. ¿Qué diferencia hay en el resultado?



**Especificar el tipo de datos**

Si no lo especificás, el tipo de datos (por omisión) de los arreglos es el punto flotante (`np.float64`). Sin embargo, podés explicitar otro tipo de datos usando la palabra clave `dtype`.

In [24]:
x = np.ones(12, dtype=np.int32)
print(x)

[1 1 1 1 1 1 1 1 1 1 1 1]


En estos dos casos el 64 de los tipos de datos se refiere a la cantidad de bits usados para representar el número en el sistema binario: 64 bits.

## Agregar, borrar y ordenar elementos

Ordenar un vector es sencillo usando `np.sort()`.
Por ejemplo, si comenzás con este vector:

In [30]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

print(np.sort(arr))

[1 2 3 4 5 6 7 8]


In [31]:
# reversa del vector
arr2 = arr[::-1]

Fijate que el vector `arr` quedó desordenado. `sort` simplemente devolvió una copia ordenada de los datos pero no modificó el original.

Otra operación usual es la concatenación. Si empezás con estos dos vectores:

In [27]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.concatenate((a, b)))

[1 2 3 4 5 6 7 8]


## Conocer el tamaño, dimensiones y forma de un arreglo


`ndarray.ndim` te dice la cantidad de ejes (o dimensiones) del arreglo.

`ndarray.shape` te va a dar una tupla de enteros que indican la cantidad de elementos en cada eje. Si tenés una matriz con 2 filas y 3 columnas de va a dar `(2, 3)`.

`ndarray.size` te dice la cantidad de elementos (cantidad de números) de tu arreglo. Es el producto de la tupla `shape`. En el ejemplo del renglón anterior, el `size` es 6.

Por ejemplo, si creás este arreglo de tres dimensiones:

In [32]:
array_ejemplo = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]],
                         )

print("Dimensiones (ndim):", array_ejemplo.ndim)
print("Forma (shape):", array_ejemplo.shape)
print("Tamaño total (size):", array_ejemplo.size)

Dimensiones (ndim): 3
Forma (shape): (3, 2, 4)
Tamaño total (size): 24


## Cambiar la forma de un arreglo

Usando `arr.reshape()` le podés dar una nueva forma a tu arreglo sin cambiar los datos. Solo tené en cuenta que antes y después del reshape el arreglo tiene que tener la misma cantidad de elementos. Por ejemplo, si comenzás con un arreglo con 12 elementos, tendrás que asegurarte que el nuevo arreglo siga teniendo 12 elementos.

Por ejemplo:

In [40]:
a = np.arange(6)
print("Original:", a)

b = a.reshape(3, 2)
print("Reshaped (3x2):\n", b)

Original: [0 1 2 3 4 5]
Reshaped (3x2):
 [[0 1]
 [2 3]
 [4 5]]


In [44]:
# Pueden hacer la traspuesta
b.T

array([[0, 2, 4],
       [1, 3, 5]])

## Índices y rebanadas (slice)

Podés indexar y rebanar arreglos de numpy como hicimos con las listas.

Para obtener elementos de un arreglo, lo más sencillo es usar los índices para seleccionar los que queremos conservar.

In [47]:
data = np.array([1, 2, 3])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


Lo podemos visualizar así:

<img src='https://raw.githubusercontent.com/mfares07/datascience/main/images/np_indexing.png' width=800 />



Otra operación muy útil es seleccionar los elementos que cumplen cierta condición. Por ejemplo, si comenzás con un arreglo así:

In [51]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print(a.shape)
print(a[a < 5])

(3, 4)
[1 2 3 4]


O conectarlos con los conectores lógicos:
<br>
`|` = OR (o)
<br>
`& `= AND (y)

In [52]:
# O más complejas:
ar = np.arange(5,20)
print(f"arange: {ar}")

# Separo condiciones entre paréntesis
filtrado = ar[(ar<8) | (ar>16)]
print(f"filtrado: {filtrado}")

# Puedo contar cuantos cumplen cierta condición
print("Encontró: ", np.sum((ar>10) & (ar%2==0)))


arange: [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
filtrado: [ 5  6  7 17 18 19]
Encontró:  4


Numpy cuenta con el módulo linalg (np.linalg). Es el conjunto de herramientas matemáticas de NumPy para hacer operaciones avanzadas con matrices y vectores.
## Ejercicio:
Resolver con Numpy el siguiente sistema de ecuaciones:
$$
\begin{cases}
5x + y = -5 \\
2x - y = 12
\end{cases}
$$


In [54]:
A = np.array([[5,1],
              [2,-1]])

b = np.array([-5,12])

np.linalg.solve(A,b)

array([  1., -10.])

## Crear arreglos usando datos existentes

Es sencillo crear un nuevo arreglo usando una sección de otro arreglo.

Supongamos que tenemos este:

In [55]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
print(arr1)

[4 5 6 7 8]


## Operaciones básicas sobre arreglos

Una vez que sabés crear arreglos podés empezar a trabajar con ellos. Imaginemos que tenés dos arreglos, uno llamado “data” y otro llamado “ones”.

<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_array_dataones.png' />

Podés sumarlos con el signo más.

In [56]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print(data + ones)

[2 3]


<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_data_plus_ones.png' />

Obviamente, podés hacer otras operaciones.

In [57]:
print("Resta:", data - ones)
print("Multiplicación:", data * data)
print("División:", data / data)

Resta: [0 1]
Multiplicación: [1 4]
División: [1. 1.]


<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_sub_mult_divide.png' />

Estas operaciones básicas son simples con numpy. Si querés calcular la suma de los elementos del arreglo, podés usar `sum()`. Esto funciona para vectores, matrices y arreglos de dimensión más alta también.

In [58]:
a = np.array([1, 2, 3, 4])
print(a.sum())

10


Para sumar los valores por fila o por columna en una matriz, simplemente tenés que especificar el eje sobre el que se hará la suma.

Si tenés la matriz:

In [59]:
b = np.array([[1, 1],
              [2, 2]])

print("Suma por columna (axis=0):", b.sum(axis=0))
print("Suma por fila (axis=1):", b.sum(axis=1))

Suma por columna (axis=0): [3 3]
Suma por fila (axis=1): [2 4]


## Broadcasting

Hay veces en que necesitás realizar una operación entre un arreglo y un número (en matemática le decimos, un _escalar_). Por ejemplo tenés un vector con distancias en millas (lo llamamos "data") y lo necesitás convertir a distancias en kilómetros. Podés hacer esta operación así:

In [60]:
data = np.array([1.0, 2.0])
print(data * 1.6)

[1.6 3.2]


<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_multiply_broadcasting.png' />

numpy entiende que la multiplicación debe ocurrir en cada celda del vector. Este concepto se llama **broadcasting**. El mecanismo de broadcasting le permite a numpy realizar operaciones en arreglos de diferente tamaño, pero los tamaños deben ser compatibles. Por ejemplo si ambos arreglos tienen el mismo tamaño o si uno tiene tamaño 1 (escalar). Si los tamaños no son compatibles, te va a dar un `ValueError`.


## Operaciones un poco más complejas

numpy también te permite realizar operaciones que resumen los datos. Además de  `min`, `max`, y `sum`, podés usar  `mean` para obtener el promedio, `prod` para calcular el producto, `std` para obtener el desvío estándar de los datos, y más.

In [61]:
data = np.array([1, 2, 3])

print("Max:", data.max())
print("Min:", data.min())
print("Sum:", data.sum())

Max: 3
Min: 1
Sum: 6


<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_aggregation.png' />

Supongamos que tenemos un arreglo, llamado “a”

In [65]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print("Suma total:", a.sum())
print("Mínimo total:", a.min())
print("Mínimo por columna:", a.min(axis=1))

Suma total: 4.8595784
Mínimo total: 0.05093587
Mínimo por columna: [0.17296777 0.05093587 0.12697628]


## Crear matrices

Podés usar listas de listas para crear arreglos bidimensionales (matrices).

In [66]:
data = np.array([[1, 2],[3, 4]])
print(data)

[[1 2]
 [3 4]]


<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_create_matrix.png' />

Las técnicas de indexación y rebanadas son muy útiles para manipular matrices:

In [67]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

2
[[3 4]
 [5 6]]
[1 3]


<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_matrix_indexing.png' />

Podés procesar los datos de matrices como lo hicimos con vectores:

In [68]:
print("Max:", data.max())
print("Min:", data.min())
print("Sum:", data.sum())

Max: 6
Min: 1
Sum: 21


<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_matrix_aggregation.png' />

Podés procesar todos, o hacerlo por fila o por columna usando el parámetro  `axis`:

In [69]:
data = np.array([[1, 2], [5, 3], [4, 6]])
print("Max por columna:", data.max(axis=0))
print("Max por fila:", data.max(axis=1))

Max por columna: [5 6]
Max por fila: [2 5 6]


<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_matrix_aggregation_row.png' />

Una vez que tenés tus matrices creadas, podés hacer artimética con pares de matrices del mismo tamaño.

In [70]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
print(data + ones)

[[2 3]
 [4 5]]


<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_matrix_arithmetic.png' />

También se pueden sumar matrices de tamaños diferentes, pero sólo si una de ellas tiene una sola fila o una sola columna. En este caso, numpy va a usar las reglas de _broadcast_ para la operación.

In [71]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
print(data + ones_row)

[[2 3]
 [4 5]
 [6 7]]


<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_matrix_broadcasting.png' />



Es frecuente que querramos inicializar los valores de una matriz. numpy ofrece las funciones `ones()` y `zeros()`, así como también la clase `random.Generator` que genera números aleatorios. Sólo hay que pasarle la cantidad de elementos que queremos generar:

In [ ]:
print("Ones:", np.ones(3))
print("Zeros:", np.zeros(3))

np.random.seed(6)
print("Random:", np.random.random(3))

<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_ones_zeros_random.png' />

También podés usar  `ones()`, `zeros()`, y `random()` para crear matrices, si le pasás una tupla describiendo la forma de la matriz:

In [80]:
print("Ones (3x2):\n", np.ones((3, 2)))
print("\nZeros (3x2):\n", np.zeros((3, 2)))
print("\nRandom (3x2):\n", np.random.random((3, 2)))

Ones (3x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Zeros (3x2):
 [[0. 0.]
 [0. 0.]
 [0. 0.]]

Random (3x2):
 [[0.19962013 0.45929669]
 [0.95535309 0.29660109]
 [0.70687101 0.62145218]]


<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_ones_zeros_matrix.png' />

Esta idea se generaliza a dimensiones más altas.



### Producto Punto
Operación entre dos vectores que devuelve un escalar, calculado como la suma de los productos de sus componentes. Indica el grado de alineación entre vectores.

In [82]:
p1 = np.array([1,2,3])
p2 = np.array([3,2,1])

print(p1.dot(p2)) # p1@p2

np.int64(10)

### Producto matricial
Multiplicación entre matrices donde cada elemento se calcula como un producto punto entre filas y columnas. Produce una nueva matriz y requiere dimensiones compatibles.


In [83]:
m1 = np.array([[1,2],[3,4],[5,6]])
m2 = np.array([[1,2,3], [3,4,5]])

m1 @ m2
# m1.dot(m2)

array([[ 7, 10, 13],
       [15, 22, 29],
       [23, 34, 45]])

<img src='https://how.okpedia.org/data/okpediaorg/prodotto-riga-per-colonna-matrice-python-2.gif' />

## Fórmulas matemáticas

La facilidad para implementar fórmulas matemáticas sobre un arreglo es una de las características de numpy que lo hacen tan ampliamente usado en la comunidad científica de Python.

Por ejemplo, ésta es la fórmula del error cuadrático medio:

<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_MSE_formula.png' width='640'/>

Implementar esta fórmula es simple y directo con numpy:

```python
mse = (1/n) * np.sum(np.square(predictions - labels))
```

<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_MSE_implementation.png' width='640' />

Lo genial de esta abstracción es que `predictions` y `labels` puede tener uno o mil valores. Sólo tienen que tener el mismo tamaño para que todo funcione.

Lo podés visulalizar así:

<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_mse_viz1.png' width='640' />

En este ejemplo, tanto las predicciones como las etiquetas tienen tres valores. Es decir `n` vale tres. Luego de hacer la resta los valores se elevan al cuadrado. Luego numpy suma los valores, divide por tres, y el resultado es el error de esa predicción y puede usarse como un _puntaje_ que mide la calidad del modelo que predice.

<img src='https://github.com/mfares07/Programacion_en_Python_UNSAM/raw/master/Notas/05_Random_Plt_Dbg/np_mse_viz2.png' width=580 />




```




```



## Ejercicio: Matriz de temperaturas y filtrado con NumPy

Generá una **matriz 30×30** de temperaturas aleatorias entre **0 °C y 50 °C** usando NumPy.

Luego, filtrá las temperaturas:
- menores a **5 °C**
- o mayores a **35 °C**

<br>

*Podés usar: `np.random.uniform()` para generar las temperaturas.
<br> y usar `np.round(...., 2)` para redondear a 2 decimales*.

In [ ]:
# @title Ver solución
temp = np.random.uniform(0,50, size=(30,30))
np.round(temp[(temp<5) |  (temp>35)], 2)